version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: coupons_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coupons_db
      MYSQL_USER: coupons_user
      MYSQL_PASSWORD: coupons_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coupons_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coupons_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: coupons_db
      NODE_ENV: development
    depends_on:
      - mysql
    networks:
      - coupons_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql_data:

networks:
  coupons_network:
    driver: bridge 